[package]
name = "tracing-indicatif"
version = "0.1.0"
edition = "2021"
description = "Automatically show indicatif progress bars for active tracing spans."
license = "MIT"
repository = "https://github.com/emersonford/tracing-indicatif"

[dependencies]
indicatif = "0.17.3"
tracing = "0.1.37"
tracing-core = "0.1.30"
tracing-subscriber = { version = "0.3.16" }

[dev-dependencies]
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["full"] }
rand = { version = "0.8.5", features = ["std_rng"] }
console = "0.15.5"

[lib]
name = "tracing_indicatif"

[[example]]
name = "basic"

[[example]]
name = "hierarchy"

[[example]]
name = "build_console"
